version: '3'

services:
  app1:
    build:
      context: ./
      dockerfile: Dockerfile
    image: serverfile
    container_name: serverfile
    hostname: serverfile
    ports:
      - 3000:3000
    networks:
      - sw2-network

networks:
  sw2-network:
    external: true
